# Introduction to Finite Frames and RIC-POVM's

Maturing out of our reflexive habit of working with orthonormal bases, we can instead work with an overcomplete basis or "frame," which can have as many elements as we like. In fact, with probability 1, any randomly chosen set of vectors ($n \ge d$) will form a frame.

Let's just think about $d=2$ real vector space. Why not a frame made of 5 vectors?

In [111]:
import numpy as np
import scipy as sc
import scipy.linalg
np.set_printoptions(precision=4, suppress=True)

d, n = 2, 5
R = np.random.randn(d, n); R

array([[ 0.4546, -0.3572,  1.4754,  0.1348, -0.1037],
       [ 0.8486,  1.0428,  1.077 ,  0.4611,  0.7134]])

We can form the Gram matrix, aka the matrix of inner products:

In [112]:
G = R.T @ R; G

array([[0.9268, 0.7225, 1.5847, 0.4525, 0.5582],
       [0.7225, 1.2151, 0.596 , 0.4327, 0.781 ],
       [1.5847, 0.596 , 3.3368, 0.6954, 0.6153],
       [0.4525, 0.4327, 0.6954, 0.2307, 0.3149],
       [0.5582, 0.781 , 0.6153, 0.3149, 0.5197]])

One condition for everything being kosher is that the Gram matrix ought to be rank-$d$.

In [113]:
np.round(np.linalg.svd(G)[1], decimals=4)

array([4.8055, 1.4236, 0.    , 0.    , 0.    ])

We should also check out:

In [114]:
R @ R.T

array([[2.5402, 1.5905],
       [1.5905, 3.6889]])

We'll have a frame if the latter has non-0 determinant aka is full rank. This means that the rows of $R$ are linearly independent.

In [115]:
np.linalg.det(R @ R.T)

6.8410026757178155

By the way, the technical definition of a frame is a set of vectors $\{v\}$, for which there are constants $a, b > 0$ such that for any vector $u$:

$$ a ||u||^2 \leq \sum_{i} |\langle u|v_{i}\rangle|^2 \leq b||u||^2 $$

The $a$ and $b$ are called frame bounds, and this definition is always satisfied if the aforementioned conditions are true. We won't be using this definition too much. 

<hr>

## Analysis and Synthesis

Suppose we have some 2D point:

In [116]:
point = np.random.randn(2); point

array([-1.5857,  2.4579])

We can expand it in terms of our frame vectors:

In [117]:
c = R.T @ point; c

array([1.3649, 3.1296, 0.3076, 0.9196, 1.9179])

 `R.T` is often called the "analysis" operator.
 
How do we recover the original point, though? 

We use the dual frame, obtained by taking the pseudo-inverse of `R`. 

The inner products with the frame vectors turn out to be the weights on the dual basis vectors, which via summation recover the original point.

In [118]:
D = np.linalg.pinv(R); D

array([[ 0.0479,  0.2094],
       [-0.4351,  0.4703],
       [ 0.5452,  0.0569],
       [-0.0345,  0.1399],
       [-0.2218,  0.289 ]])

In [119]:
sum([c[i]*D[i] for i in range(n)])

array([-1.5857,  2.4579])

Or:

In [120]:
D.T @ c

array([-1.5857,  2.4579])

`D.T` is often called the "synthesis" operator.

It works because:

In [121]:
D.T @ R.T 

array([[ 1., -0.],
       [-0.,  1.]])

Conversely, we could have expanded in the dual basis:

In [122]:
c = D @ point; c

array([ 0.4388,  1.8458, -0.7248,  0.3985,  1.062 ])

In [123]:
R @ c

array([-1.5857,  2.4579])

<hr>

Another way of thinking about this "recovery" procedure: instead, we could take the pseudo-inverse of the Gram matrix. 

In [124]:
Ginv = np.linalg.pinv(G); Ginv

array([[ 0.0461,  0.0776,  0.038 ,  0.0276,  0.0499],
       [ 0.0776,  0.4104, -0.2105,  0.0808,  0.2324],
       [ 0.038 , -0.2105,  0.3005, -0.0109, -0.1045],
       [ 0.0276,  0.0808, -0.0109,  0.0208,  0.0481],
       [ 0.0499,  0.2324, -0.1045,  0.0481,  0.1327]])

If we have our frame coordinates:

In [125]:
c = R.T @ point; c

array([1.3649, 3.1296, 0.3076, 0.9196, 1.9179])

Acting with $G^{-1}$ will give us the coordinates in the dual basis:

In [126]:
Ginv @ c

array([ 0.4388,  1.8458, -0.7248,  0.3985,  1.062 ])

So that:

In [127]:
R @ Ginv @ c

array([-1.5857,  2.4579])

In other words, using $G^{-1}$, we can avoid explicitly invoking the dual basis.

<hr>

## Tight Frames

We might consider restrictions on our frames. Different kinds of frames are useful for different purposes. 

For example, everyone loves tight frames. We can get one via a generalization of a polar decomposition for rectangular matrices. Starting with a random $d \times n$ matrix $R$, we decompose as $R = UH$, where the rows of $U$ are orthonormal, and $H$ is Hermitian. Then we throw out the $H$ part.

In [128]:
R = np.random.randn(d, n)
R = sc.linalg.polar(R)[0]; R

array([[ 0.4898,  0.1454,  0.3816,  0.7698, -0.0268],
       [-0.6428,  0.584 ,  0.4865,  0.06  ,  0.0741]])

In [129]:
R.T @ R

array([[ 0.653 , -0.3042, -0.1258,  0.3384, -0.0607],
       [-0.3042,  0.3623,  0.3396,  0.147 ,  0.0394],
       [-0.1258,  0.3396,  0.3823,  0.323 ,  0.0258],
       [ 0.3384,  0.147 ,  0.323 ,  0.5962, -0.0162],
       [-0.0607,  0.0394,  0.0258, -0.0162,  0.0062]])

The point is that:

In [130]:
R @ R.T

array([[1., 0.],
       [0., 1.]])

So the frame is the same as its dual! In other words, the analysis operator is `R.T` and the synthesis operator is `R`.

In [131]:
point

array([-1.5857,  2.4579])

In [132]:
c = R.T @ point; c

array([-2.3565,  1.205 ,  0.5906, -1.0731,  0.2245])

In [133]:
R @ c

array([-1.5857,  2.4579])

More generally, any frame for which $R R^{\dagger}$ is proportional to the identity is a "tight frame," so that the dual frame is proportional to the original frame. In terms of the "frame bounds" from before, a tight frame means that $a=b$. And when $a=b=1$, this is known as a "Parseval frame."

Also, for a tight frame, the Gram matrix is a rank-$d$ projector.

In [134]:
np.linalg.eig(R.T @ R)[0]

array([ 0.,  1.,  1., -0., -0.])

<hr>

## Unit Norm Tight Frames

We might also be interested not just in tight frames, but in "unit norm tight frames". As the name suggests, each vector has unit norm. 

One easy way to get one is to alternate between "tightening" and "normalizing" our vectors until we're satisfied.

In [135]:
def random_funtf(d, n, rtol=1e-15, atol=1e-15):
    R = np.random.randn(d, n)
    done = False
    while not (np.allclose(R @ R.T, (n/d)*np.eye(d), rtol=rtol, atol=atol) and\
               np.allclose(np.linalg.norm(R, axis=0), np.ones(n), rtol=rtol, atol=atol)):
        R = sc.linalg.polar(R)[0]
        R = np.array([state/np.linalg.norm(state) for state in R.T]).T
    return R

In [136]:
R = random_funtf(2, 5); R

array([[-0.201 , -0.7607,  0.6446,  0.7488,  0.9513],
       [-0.9796,  0.6492, -0.7646,  0.6628,  0.3084]])

In [137]:
R.T @ R

array([[ 1.    , -0.483 ,  0.6194, -0.7998, -0.4933],
       [-0.483 ,  1.    , -0.9866, -0.1393, -0.5234],
       [ 0.6194, -0.9866,  1.    , -0.0241,  0.3773],
       [-0.7998, -0.1393, -0.0241,  1.    ,  0.9167],
       [-0.4933, -0.5234,  0.3773,  0.9167,  1.    ]])

In [138]:
R @ R.T

array([[2.5, 0. ],
       [0. , 2.5]])

Notice that we've had to demand $RR^{\dagger}$ to be $\frac{n}{d} I$.

In [139]:
point

array([-1.5857,  2.4579])

In [140]:
c = R.T @ point; c

array([-2.089 ,  2.8017, -2.9013,  0.4419, -0.7503])

In [141]:
(d/n)*R @ c

array([-1.5857,  2.4579])

<hr>

## Equiangular Frames

As I say, there are many kinds of frames that people are interested in, which have various geometric and/or information theoretic properties.

One of the classics of the genre are the so-called "equiangular frames," which are made up of vectors which form equal angles with each other (or more properly, the absolute values of the inner products are all the same).

These are great for many reasons, not least because they provide very resilient representations of data even if you should lose a few components.

There are, however, geometrical restrictions on the maximum number of equiangular lines you can have in a given dimension. For example, in $d=2$, you can have a maximum of $3$ equiangular lines. 

The $3$ are easy to construct:

In [142]:
R = np.array([[r.real, r.imag] for r in [np.exp(2j*np.pi*i/3) for i in range(3)]]).T; R

array([[ 1.   , -0.5  , -0.5  ],
       [ 0.   ,  0.866, -0.866]])

In [143]:
R.T @ R

array([[ 1. , -0.5, -0.5],
       [-0.5,  1. , -0.5],
       [-0.5, -0.5,  1. ]])

In [144]:
R @ R.T

array([[1.5, 0. ],
       [0. , 1.5]])

The 3 lines form the diagonals of a hexagon. 

<img src="img/hexagon.jpg">

<hr>

In three dimensions, an equiangular frame is provided by the icosahedron, which has 20 faces and 12 vertices: its six diagonals provide the frame vectors.

<img width=300 src="img/icosahedron.png">

In [145]:
def circular_shifts(v): 
    """
    Returns all shifted versions of a vector, e.g.:
        [1,2,3]
        [3,1,2]
        [2,3,1]
    """
    shifts = [v]
    for i in range(len(v)-1):
        u = shifts[-1][:]
        u.insert(0, u.pop()) 
        shifts.append(u)
    return shifts

def icosahedron_frame():
    """
    Returns equiangular frame based on the icosahedron in three dimensions.
    """
    phi = (1+np.sqrt(5))/2 # golden ratio
    # 12 vertices provided by circular shifts of the four vectors
    vertices = [np.array(v) for v in 
                   circular_shifts([0, 1, phi]) + \
                   circular_shifts([0, -1, -phi]) + \
                   circular_shifts([0, 1, -phi]) + \
                   circular_shifts([0, -1, phi])]
    # throw out the antipodal vectors
    keep = []
    for i, a in enumerate(vertices):
        for j, b in enumerate(vertices):
            if i != j and np.allclose(a, -b) and j not in keep:
                keep.append(i)
    # normalize
    return np.array([e/np.linalg.norm(e) for i, e in enumerate(vertices) if i in keep]).T

In [146]:
R = icosahedron_frame(); R

array([[ 0.    ,  0.8507,  0.5257,  0.    , -0.8507,  0.5257],
       [ 0.5257,  0.    ,  0.8507,  0.5257,  0.    , -0.8507],
       [ 0.8507,  0.5257,  0.    , -0.8507,  0.5257,  0.    ]])

In [147]:
R.T @ R

array([[ 1.    ,  0.4472,  0.4472, -0.4472,  0.4472, -0.4472],
       [ 0.4472,  1.    ,  0.4472, -0.4472, -0.4472,  0.4472],
       [ 0.4472,  0.4472,  1.    ,  0.4472, -0.4472, -0.4472],
       [-0.4472, -0.4472,  0.4472,  1.    , -0.4472, -0.4472],
       [ 0.4472, -0.4472, -0.4472, -0.4472,  1.    , -0.4472],
       [-0.4472,  0.4472, -0.4472, -0.4472, -0.4472,  1.    ]])

In [148]:
R @ R.T

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

<hr>

Check out <a href="examples/frame_viz.py">frame_viz.py</a> to play around with different kinds of 2D frames! 

You'll be able to drag around a point in 2D. Press `c` to show standard Cartesian axes, and the projections of the point onto them. Press `f` to show the frame vectors and the projections onto them. Press `d` to show the dual vectors and the projections onto them. Press `q` to show the reconstruction of the point by a weighted sum of frame vectors (provided by the inner products with the dual vectors). Press `p` to show the reconstruction of the point by a weighted sum of dual vectors (provided by the inner products with the frame vectors).

Note that to get the projections right, we need to divide frame (dual) coordinates by the norm squared of the corresponding frame (dual) vectors. 

Because:

In [149]:
R = np.random.randn(2, 3); R

array([[ 0.2093, -0.4849,  0.8807],
       [ 0.2474,  0.1251, -1.4777]])

In [150]:
point

array([-1.5857,  2.4579])

If we want to project the point onto the three frame vectors, we can use the projectors formed from the outer products $rr^{T}$, where $r$ is unit norm. This amounts to dividing by $||r||^2$.

In [151]:
np.array([np.outer(r/np.linalg.norm(r), r/np.linalg.norm(r))@point for r in R.T])

array([[ 0.5505,  0.6508],
       [-2.0814,  0.5371],
       [-1.4966,  2.511 ]])

Meanwhile, we have our inner products:

In [152]:
c = R.T @ point; c

array([ 0.2762,  1.0764, -5.0286])

To recover the projections, we multiply each of the inner products by the vector, divided by the norm squared.

In [153]:
np.array([c[i]*R.T[i]/np.linalg.norm(R.T[i])**2 for i in range(3)])

array([[ 0.5505,  0.6508],
       [-2.0814,  0.5371],
       [-1.4966,  2.511 ]])

Finally, in the case of 2D, we have another way of visualizing things. Press `3` to check it out.

We can interpret the three inner products with the frame vectors as a point in 3D. 

In [154]:
c

array([ 0.2762,  1.0764, -5.0286])

Moreover, `D` will be a $3 \times 2$ matrix: we can interpret its 2 columns as specifying two vectors in 3D.

In [155]:
D = np.linalg.pinv(R); D

array([[ 1.1956,  0.8025],
       [-1.3979, -0.755 ],
       [ 0.0818, -0.6063]])

We can project our 3D point onto these two vectors:

In [156]:
[np.outer(D.T[i], D.T[i])/np.linalg.norm(D.T[i])**2 @ c for i in range(2)]

[array([-0.5592,  0.6538, -0.0382]), array([ 1.2471, -1.1733, -0.9423])]

But this is just the same as weighting each of the two vectors by the Cartesian coordinates of the original point!

In [157]:
[point[i]*D.T[i]/np.linalg.norm(D.T[i])**2 for i in range(2)]

[array([-0.5592,  0.6538, -0.0382]), array([ 1.2471, -1.1733, -0.9423])]

In other words, the three inner products with the frame vector specify a point in 3D. The dual basis specifies two linearly independent axes in 3D. The projection of the 3D point onto these two axes gives two coordinates: these are proportional to the original 2D point in Cartesian coordinates.

<hr>

## RIC-POVM's


Now consider that $3$ is also the dimension of the space of $2 \times 2$ symmetric matrices. 

Indeed, we might be interested in this fact if we wanted to do real vector space quantum mechanics. 

In real quantum mechanics, pure states are given by 2D vectors $\mid \psi \rangle = \begin{pmatrix}x \\ y \end{pmatrix}$ such that $x^2 + y^2 = 1$, aka points on the circle; or better yet: rank-1 density matrices: $\mid \psi \rangle \langle \psi \mid = \begin{pmatrix}x^2 & xy \\ xy & y^2 \end{pmatrix}$. 

More generally, a density matrix might be a higher rank statistical mixture. Any symmetric, positive semi-definite matrix with unit trace will do.

Now here's the big reveal: it turns out that tight frames are just rank-1 POVM's in disguise. 

Recall that a POVM, or positive operator valued measure, is a set of positive semi-definite matrices that sum to the identity: $\sum_{i} E_{i} = I$. Each "element" represents an outcome to a generalized quantum measurement that concretely involves entangling your quantum system to an apparatus (with a dimensionality equal to the number of POVM elements) and doing a standard (Von Neumann) measurement on the latter. In the case of a rank-1 POVM, the outcome states of the original sytem will correspond to the normalized POVM elements.

A POVM can have any number of elements (well, I suppose at least two!): but we're interested in "informationally complete" POVM's, which have as many elements as the dimensions of the relevant operator space, aka the space of density matrices, which for real vector space is $\frac{d(d+1)}{2}$. (In complex quantum mechanics, we use not symmetric matrices, but Hermitian matrices, which have $d^2$ parameters.) 

If we have enough elements to span the operator space, then the vector of probabilities for each outcome suffice to completely determine the quantum state. And so, among other things, we can do quantum tomography, treating pure states and mixed states on an equal footing, by repeating one measurement over and over again on many copies of a system, instead of having to do different, complementary measurements.

We can upgrade a tight frame into a rank-1 POVM by taking the outer products of the vectors with themselves. (And by the way, it's not at all necessary that POVM elements be rank-1: those we'll be considering here, however, will be.) The POVM condition, as you can see, is satisfied since $RR^{\dagger}$ amounts to $\sum_{i} |r\rangle\langle r|$.

In [158]:
d, n = 2, 3
R = sc.linalg.polar(np.random.randn(d, n))[0]
R @ R.T

array([[1., 0.],
       [0., 1.]])

In [159]:
E = [np.outer(r, r) for r in R.T]
sum(E)

array([[1., 0.],
       [0., 1.]])

Given a random density matrix:

In [160]:
def rand_dm(d, n=2):
    # n controls the degree of mixedness
    A = np.random.randn(d, n)
    rho = A @ A.T
    return rho/rho.trace()

rho = rand_dm(2); rho

array([[0.7393, 0.4366],
       [0.4366, 0.2607]])

We can expand it in terms of POVM elements:

In [161]:
p = np.array([(e @ rho).trace() for e in E]); p

array([0.143, 0.776, 0.081])

In [162]:
sum(p)

1.0000000000000002

The components sum to 1: they are the probabilities for the outcomes to this experiment. 

<hr>

Now how do we get the density matrix back? The dual basis, of course! But how do we find it?

Given a matrix $A$, denote by $|A\rangle \rangle$ the vector you get by reshaping the matrix into a vector. 

(If you want to be fancy, you can think of this like $\sum_{i} (A \otimes I)\mid i \rangle\mid i \rangle$, or as $A$ acting on the left on the maximally entangled "cup" state on the doubled Hilbert space, $H_{d} \otimes H_{d}$).

Then form the "(operator) frame operator":

$F = \sum_{i} \mid E_{i} \rangle \rangle \langle \langle E_{i} \mid$

Next, take its (pseudo) inverse. Finally, $F^{-1}\mid E_{i}\rangle \rangle = \mid \tilde{E}_{i} \rangle \rangle$, where $\tilde{E}$ is the dual basis. 

In [163]:
F = sum([np.outer(e.reshape(d**2), e.reshape(d**2)) for e in E])
Finv = np.linalg.pinv(F)
D = [(Finv @ e.reshape(d**2)).reshape(d,d) for e in E]

Then, we can recover the original density matrix by weighting the elements of the dual basis by the probabilities and summing:

In [164]:
rho

array([[0.7393, 0.4366],
       [0.4366, 0.2607]])

In [165]:
sum([p[i]*D[i] for i in range(n)])

array([[0.7393, 0.4366],
       [0.4366, 0.2607]])

Conversely, we could expand in dual elements:

In [166]:
q = np.array([(e @ rho).trace() for e in D]); q

array([ 4.1493,  0.5355, -0.1605])

And recover the original density matrix by weighting POVM elements and summing

In [167]:
sum([q[i]*E[i] for i in range(n)])

array([[0.7393, 0.4366],
       [0.4366, 0.2607]])

By the way, the dual basis of an informationally complete POVM <a href="https://physics.stackexchange.com/questions/588467/dual-of-ic-povm-cannot-be-positive">doesn't form a POVM itself</a>. Indeed, its elements must be indefinite!

<hr>

Alternatively, instead of working with the dual basis directly, we could play a similar trick from before. 

Instead of taking $G^{-1}$, now we take $(G \circ G )^{-1}$ where $\circ$ is the Hadamard (element-wise) square. Instead of expanding in the dual basis, we can act with $(G \circ G )^{-1}$ on the vector of probabilities to get the proper weights for POVM elements required to recover $\rho$.

In [168]:
rho

array([[0.7393, 0.4366],
       [0.4366, 0.2607]])

In [169]:
p

array([0.143, 0.776, 0.081])

In [170]:
G = R.T @ R
Gsq_inv = np.linalg.inv(G**2)

In [171]:
q = Gsq_inv @ p; q

array([ 4.1493,  0.5355, -0.1605])

We can now get our density matrix back:

In [172]:
sum([q[i]*E[i] for i in range(n)])

array([[0.7393, 0.4366],
       [0.4366, 0.2607]])

<hr>

But we can do a little bit more, which will prove useful.

We could form a matrix of conditional probabilities supposing we repeat our POVM twice. In other words, a matrix of conditional probabilities: 

$$ Pr(E_{i}|E_{j}) = tr(E_{i}\frac{E_{j}}{tr(E_{j})})$$

After the first measurement, we end up in some $\frac{E_{j}}{tr(E_{j})}$, and then we look at the probabilities that we get some $E_{i}$.


In [173]:
E_given_E = np.array([[(E[i]@(E[j]/E[j].trace())).trace() for j in range(n)] for i in range(n)]); E_given_E

array([[0.1609, 0.0912, 0.0562],
       [0.5115, 0.9019, 0.0066],
       [0.3276, 0.0068, 0.9372]])

Notice that this related to $(G \circ G )$, except for the fact that we divide by $tr(E_{j})$. 

We can take its inverse to obtain the "Born matrix" $\Phi$:

In [174]:
phi = np.linalg.inv(E_given_E); phi

array([[11.1201, -1.1198, -0.6594],
       [-6.2784,  1.741 ,  0.3645],
       [-3.8416,  0.3788,  1.2949]])

What's the point? If we take our density matrix:

In [175]:
rho

array([[0.7393, 0.4366],
       [0.4366, 0.2607]])

And its probabilities:

In [176]:
p

array([0.143, 0.776, 0.081])

Then we can form:

In [177]:
q = phi @ p; q

array([ 0.6675,  0.483 , -0.1504])

In [178]:
sum(q)

1.0000000000000004

This is nice, because by acting on our vector of probabilities with $\Phi$, we get back a vector of *quasi-probabilities*: while the components might be negative, they nevertheless sum to 1. And this will prove to be useful.

We can then get our density matrix back by summing over normalized elements of our POVM, weighted by the quasi-probabilities.

In [179]:
sum([q[i]*E[i]/E[i].trace() for i in range(n)])

array([[0.7393, 0.4366],
       [0.4366, 0.2607]])

Moreover, we can also obtain this matrix $\Phi$ from the dual elements. Actually, it's nicer to renormalize the dual elements first so that they have the same weights as the POVM elements.

In [180]:
D = [E[i].trace()*D[i] for i in range(n)]
sum(D)

array([[ 1.,  0.],
       [-0.,  1.]])

In [181]:
D_given_D = np.array([[(D[i]@(D[j]/D[j].trace())).trace() for j in range(n)] for i in range(n)]); D_given_D

array([[11.1201, -1.1198, -0.6594],
       [-6.2784,  1.741 ,  0.3645],
       [-3.8416,  0.3788,  1.2949]])

Expanding in renormalized dual elements gives us our quasiprobabilities:

In [182]:
q = np.array([(d @ rho).trace() for d in D]); q

array([ 0.6675,  0.483 , -0.1504])

And as before:

In [183]:
sum([q[i]*E[i]/E[i].trace() for i in range(n)])

array([[0.7393, 0.4366],
       [0.4366, 0.2607]])

And symmetrically:

In [184]:
sum([p[i]*D[i]/D[i].trace() for i in range(n)])

array([[0.7393, 0.4366],
       [0.4366, 0.2607]])

<hr>

## Deforming the Law of Total Probability

Okay, but why should we care?

We're going to consider two measurements on our quantum system, $A$ and $B$, where $A$ is an IC-POVM, and $B$ could be a standard Von Neumann measurement or a POVM, doesn't matter. Let's say it's an IC-POVM.

In [185]:
d, n = 2, 3
A = [np.outer(r, r) for r in sc.linalg.polar(np.random.randn(d, n))[0].T]
B = [np.outer(r, r) for r in sc.linalg.polar(np.random.randn(d, n))[0].T]

In [186]:
rho

array([[0.7393, 0.4366],
       [0.4366, 0.2607]])

We can of course nail down our quantum state by its probabilities on measurement $A$.

In [187]:
p_A = np.array([(a @ rho).trace() for a in A]); p_A

array([0.1037, 0.0005, 0.8958])

Now we're going to compare two sequences of events.

First: we measure $A$, and then measure $B$. Before we look at the outcome for $A$, however, what probabilities should we assign to the outcomes of $B$?

To figure this out, we could use a matrix of conditional probabilities:

In [188]:
B_given_A = np.array([[(b@a/a.trace()).trace() for a in A] for b in B]); B_given_A

array([[0.9642, 0.9582, 0.0177],
       [0.0001, 0.0083, 0.0489],
       [0.0358, 0.0335, 0.9335]])

These are the conditional probabilities for each of $B$'s outcomes, given each outcome state of $A$. This gives us conditional probabilities $Pr(B_{i}|A_{j})$. 

We end up with a column stochastic matrix:

In [189]:
np.sum(B_given_A, axis=0)

array([1., 1., 1.])

We can then use the law of total probability: $Pr(B_{i}) = \sum_{j} Pr(B_{i}|A_{j}) Pr(A_{j})$.

In [190]:
p_AB = B_given_A @ p_A; p_AB

array([0.1163, 0.0438, 0.8399])

In [191]:
sum(p_AB)

1.0

We can check this. After the measurement of $A$, we should regard our system's state as a statistical mixture of $A$'s outcomes, weighted by the probability of their occurance:

In [192]:
rho_post_A = sum([p_A[i]*a/a.trace() for i, a in enumerate(A)]); rho_post_A

array([[0.8505, 0.1846],
       [0.1846, 0.1495]])

We can then get the $B$ probabilities for this density matrix by taking inner products with $B$'s elements.

In [193]:
p_AB2 = np.array([(b @ rho_post_A).trace() for b in B]); p_AB2

array([0.1163, 0.0438, 0.8399])

In [194]:
sum(p_AB2)

1.0

We get the same probabilities. 

<hr>

To recap: we did measurement of $A$, but didn't look at the answer. We just wanted the probabilities for the future measurement $B$. So we used the law of total probability: $p(B_{i}) = \sum_{j} p(B_{i}|A_{j}) p(A_{j})$.

Okay. 

The second experiment is that we leave $A$ hypothetical, but instead just do the $B$ measurement. We know what the answer should be: we just expand in terms of $B$.

In [195]:
p_B = np.array([(b @ rho).trace() for b in B]); p_B

array([0.0289, 0.0421, 0.9289])

But since our probabilities on $A$ completely nail down the state, there ought to be a way of getting these latter probabilities in terms of them...

It's easy! We simply form the "Born matrix" $\Phi$ from before:

In [196]:
phi = np.linalg.inv([[(a1 @ a0/a0.trace()).trace() for a0 in A] for a1 in A])

And instead of doing:

In [197]:
B_given_A @ p_A 

array([0.1163, 0.0438, 0.8399])

We do:

In [198]:
B_given_A @ phi @ p_A 

array([0.0289, 0.0421, 0.9289])

Hence the name the "Born matrix": it allows us to recover the Born rule. Notice how everything is still formulated in terms of a) the conditional probability matrix for B's outcomes given A's outcomes, and b) the probability vector for A's outcomes. 

One can now see the usefulness of:

In [199]:
q = phi @ p_A; q

array([ 0.7857, -0.7786,  0.993 ])

In [200]:
sum(q)

0.9999999999999999

The fact that $\Phi$ takes us to quasiprobabilities makes sure we play nicely with the conditional probability matrix.

Another way of thinking about this is to form a "conditional quasiprobability matrix":

$$ Qr(B_{i}|\tilde{A}_{j}) = tr(B_{i}\frac{\tilde{A}_{j}}{tr(\tilde{A}_{j})})$$


In [201]:
FA = sum([np.outer(e.reshape(d**2), e.reshape(d**2)) for e in A])
FAinv = np.linalg.pinv(FA)
DA = [e.trace()*(FAinv @ e.reshape(d**2)).reshape(d,d) for e in A]
B_given_DA = np.array([[(B[i]@(DA[j]/DA[j].trace())).trace() for j in range(n)] for i in range(n)]); B_given_DA

array([[ 0.5994,  3.6002, -0.039 ],
       [-0.0122,  0.0873,  0.0484],
       [ 0.4128, -2.6875,  0.9906]])

Then:

In [202]:
B_given_DA @ p_A

array([0.0289, 0.0421, 0.9289])

Indeed:

In [203]:
np.allclose(B_given_DA, B_given_A@phi)

True

Perhaps more concretely:

If we perform POVM $A$, then:

$$ \rho \rightarrow \rho^{\prime} = \sum_{i} Pr(A_{i}|\rho)\frac{A_{i}}{tr(A_{i})}$$

If we *don't* perform POVM $A$, then:

$$ \rho \rightarrow \sum_{i} Pr(A_{i}|\rho)\frac{\tilde{A}_{i}}{tr(\tilde{A}_{i})}$$

Which is just $\rho$! 

If we perform POVM $A$, and then POVM $B$:

$$ \rho \rightarrow \sum_{i} \Big{(} \sum_{j} Pr(B_{i}|A_{j}) Pr(A_{j}|\rho) \Big{)} \frac{B_{i}}{tr(B_{i})} = \sum_{i} Pr(B_{i}|\rho^{\prime}) \frac{B_{i}}{tr(B_{i})}$$

If we *don't* perform POVM $A$, and then do perform POVM $B$:

$$ \rho \rightarrow  \sum_{i} \big{(} \sum_{j} Qr(B_{i}|\tilde{A}_{j}) Pr(A_{j}|\rho) \big{)} \frac{B_{i}}{tr(B_{i})} =  \sum_{i} Pr(B_{i}|\rho)  \frac{B_{i}}{tr(B_{i})} $$

And if we did neither:

$$ \rho \rightarrow  \sum_{i} \big{(} \sum_{j} Qr(B_{i}|\tilde{A}_{j}) Pr(A_{j}|\rho) \big{)} \frac{\tilde{B}_{i}}{tr(\tilde{B}_{i})} =  \sum_{i} Pr(B_{i}|\rho)  \frac{\tilde{B}_{i}}{tr(\tilde{B}_{i})} $$

Which is just $\rho$!


<hr>

## Quantumness 

So in the first case, we did $A$, and afterwards we described our system as a mixed state of A's outcomes, weighted by the probability of them happening. No "coherence" between outcomes: there's just "classical ignorance." And we used the old school law of total probability to get the probabilities for the outcomes of $B$.

In the second case, we didn't do $A$: and so "quantum coherence" was preserved. But we could still get the probabilities for a $B$ measurement from the probabilities of the (hypothetical) $A$ measurement.

One way of thinking of this is that quantum mechanics encourages us to modify the law of total probability. Classically speaking, we could use the law of total probability whether or not we did an intermediate measurement of $A$ before $B$. But quantum mechanically, it matters. If we don't do $A$, we have to stick the Born matrix $\Phi$ in between the conditional probability matrix and the probability vector. In matrix notation, instead of $\vec{Pr(B_{i})} = \hat{Pr(B_{i}|A_{j})}\vec{Pr(A_{j})}$, we have $\vec{Pr(B_{i})} = \hat{Pr(B_{i}|A_{j})}\hat{\Phi}\vec{Pr(A_{j})}$.

Now, if $\Phi$ were the identity, then there would be no difference, as it were, between classical and quantum. No coherence, everything having "objective properties," law of total probability always valid, etc. The lesson of quantum mechanics is that: $\Phi$ is not the identity.

So you might wonder: what measurements are associated with a $\Phi$ such that $\Phi$ is *as close to the identity as possible*?

With this in mind, we form a quantity we'll call "quantumness": $Q = ||\Phi - I||$.

In [204]:
def quantumness(E):
    phi = np.linalg.inv([[(e1@e0/e0.trace()).trace() for e0 in E] for e1 in E])
    return np.linalg.norm(phi - np.eye(len(E)))

In [205]:
quantumness(A), quantumness(B)

(37.01558922121932, 273.4549974104693)

This quantity diagnoses the extent to which the law of total probability is deformed.


Now it's known that SIC-POVM's aka "symmetrically informationally complete POVM's," which correspond to equiangular lines, minimize quantumness. And in fact, the proof that they do so doesn't depend on the particulars of which norm you choose to measure the difference between $\Phi$ and the identity. 

In other words, and it makes sense, SIC-POVM's, whose elements all make the same angle with each other, have $\Phi$ matrices as close to the identity as possible. They are the quantum measurements that are "irreducibly quantum."

Now much of the study of SIC-POVM's takes place in the context of *real* quantum mechanics, I mean, complex vector space quantum mechanics. In this case, SIC-POVM's would correspond to *complex equiangular lines*, which are a bit more difficult to visualize. And to span the space of density matrices, you'd need $d^2$ of them for dimension $d$.

For example, in the case of $d=2$, the four elements of a SIC-POVM make up the vertices of a regular tetrahedron on the Bloch sphere. 

It's been conjectured, and widely believed, on the basis of a great deal of theoretical and computational effort, that SIC-POVM's exist in all complex dimensions. And conditional on this being true, then we know the irreducibly quantum measurements in any dimension: they are the SIC's.

<hr>

Here's the thing, though. 

As I've said: in real quantum mechanics, RIC-POVM's (real informationally complete POVM's) require $n=\frac{d(d+1)}{2}$ elements. As we've seen, this is fine for $d=2$: in this case, $n=3$, and we have the "Mercedes-Benz" frame. So too, all is well in $d=3$. Then $n=6$, and we have our icosahedron.

But then the shit hits the fan. 

Here's a table listing the known maximum number of equiangular lines in different real dimensions compared to the dimensionality of the symmetric operator space. 

I've starred the ones where SIC-POVM's can exist, namely: 2, 3, 7, 23 (so far as we know).

| d | max| n |
|---|-----|----------------|
| 2 |  3  |  3* |
| 3 |  6  |  6*|
| 4 |  6  |  10|
| 5 | 10  |  15|
| 6 | 16  |  21|
| 7 | 28 |  28*|
| 8 | 28 | 36|
| 9 | 28 | 45|
| 10 | 28 | 55|
| 11 | 28 | 66|
| 12 | 28 | 78|
| 13 | 28 | 91|
|14 | 28-30| 105|
|15 | 36 | 120|
|16 | 40-42| 136|
|17 | 48-50| 153|
|18 | 48-61| 171|
|19 | 72-76| 190|
|20 | 90-96| 210|
|21 | 126 | 231|
|22 | 176 | 253|
|23 | 276 | 276*|

(Incidentally, the famous Gerzon bound says there definitely can't be more that $\frac{d(d+1)}{2}$ equiangular lines in $\mathbb{R}^n$).

You might wonder: given that (unlike in the complex case), we definitely know there aren't SIC's in all real dimensions, what's the *next best thing*? Specifically, what are the RIC's with lowest quantumness in each real dimension where a SIC doesn't exist? 

It's an open question!

<hr>

## Bibliography

<a href="https://www.math.auckland.ac.nz/~waldron/Preprints/Frame-book/draft26-7.17.pdf">
An Introduction to Finite Tight Frames</a>

<a href="https://faculty.sites.iastate.edu/esweber/files/inline-files/book_final.pdf">Frames for Undergraduates</a>

<a href="http://www1.chapman.edu/~mbvajiac/conferences/chapman_lec03_slides.pdf">Slides on Frame Theory</a>
    
<a href="https://arxiv.org/abs/1311.3219">New bounds for equiangular lines</a>

<a href="https://www.lib.uidaho.edu/digital/etd/items/oldroyd_idaho_0089e_10817.html">Generalizations and Approximations of Equiangular Tight Frames</a>

<a href="https://arxiv.org/abs/1812.08762">The Varieties of Minimal Tomographically Complete Measurements</a>

<a href="https://arxiv.org/abs/1805.08721">Symmetric Informationally Complete Measurements Identify the Irreducible Difference between Classical and Quantum Systems</a>

<a href="https://arxiv.org/abs/quant-ph/0310075">Symmetric Informationally Complete Quantum Measurements</a>

<a href="https://arxiv.org/abs/1911.05809">Sporadic SICs and Exceptional Lie Algebras</a>